name: Compilar APK do Totem

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Baixar Codigo do Repositorio
      uses: actions/checkout@v4

    - name: Configurar Java JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Instalar Dependencias do Linux e Buildozer
      run: |
        sudo apt update
        sudo apt install -y git zip unzip python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libssl-dev cmake libffi-dev libgomp1
        pip3 install --user buildozer

    - name: Compilar APK
      run: |
        # Cria a pasta de licenças que o Android SDK exige para não travar o build
        mkdir -p ~/.android
        touch ~/.android/repositories.cfg
        
        # Roda o Buildozer aceitando os termos automaticamente e mostrando o log detalhado
        yes | ~/.local/bin/buildozer -v android debug --log_level=2
