name: Compilar APK do Totem

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Baixar Codigo
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Configurar Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Instalar Dependencias Nativas
      run: |
        sudo apt update
        sudo apt install -y git zip unzip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libssl-dev cmake libffi-dev libgomp1 gcc g++ make patch lldb libasound2-dev libpulse-dev gperf bison flex libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev
        pip3 install --user "buildozer==1.5.0" "Cython==0.29.36" virtualenv

  - name: Compilar APK
      run: |
        export PATH=$PATH:$HOME/.local/bin
        unset ANDROID_NDK ANDROID_NDK_HOME ANDROID_NDK_ROOT ANDROID_NDK_LATEST_HOME
        rm -rf .buildozer/bin/
        rm -rf .buildozer/android/platform/build-*
        buildozer -v android debug

    - name: Guardar o APK para Download
      uses: actions/upload-artifact@v4
      with:
        name: TotemMidia-APK
        path: bin/*.apk
